language: python
python:
  - 3.6
  - 3.7
  - 3.8
os: linux
dist: xenial
install:
  - sudo apt-get update
  - sudo apt install python3-pip
  - sudo -H pip3 install setuptools
  - sudo -H pip3 install aiohttp
script:
  - ./run_tests